In [20]:
import numpy
initArr = numpy.empty([81], dtype=int) #array that contains the original file

#open input file
infilename = 'sudoku1'
file = open(infilename, 'r')

#populate empty array using the file
i=0
c = file.read(1)
while len(c) > 0:
    if len(c.strip()) > 0: 
        initArr[i]=c
        i=i+1
    c = file.read(1)    
file.close()

#turn array to 2D array
initArr = initArr.reshape(9,9)

#copy the array to a new array
newArr = numpy.empty([9,9], dtype=int) 
newArr = numpy.copy(initArr) 

#checks if num is in the col'th column of array arr
def incol (arr, col, num):
#{
    if num == 0:
        print('ERROR INCOL FNC')
        
    i = False
    for item in arr[:,col]:
        if item == num:
            i = True
            break
    return i
#}

#checks if num is in the row'th row of array arr
def inrow (arr, row, num):
#{
    if num == 0:
        print('ERROR INROW FNC')
    
    i = False
    for item in arr[row]:
        if item == num:
            i = True
            break
    return i    
#}

#checks if num is in the 3x3 box of (col,row)
def in3x3 (arr, col, row, num):
#{
    if num == 0:
        print('ERROR IN3X3 FNC')
        
    i = False
    subarr = numpy.empty([3,3], dtype=int)
    
    #get 3x3 subarray
    if  ((0 <= row <= 2) and (0 <= col <= 2)):
        subarr = arr[0:3, 0:3]
    elif((3 <= row <= 5) and (0 <= col <= 2)):
        subarr = arr[3:6, 0:3]
    elif((6 <= row <= 8) and (0 <= col <= 2)):
        subarr = arr[6:9, 0:3]    
    elif((0 <= row <= 2) and (3 <= col <= 5)):
        subarr = arr[0:3, 3:6]    
    elif((0 <= row <= 2) and (6 <= col <= 8)):
        subarr = arr[0:3, 6:9]            
    elif((3 <= row <= 5) and (3 <= col <= 5)):
        subarr = arr[3:6, 3:6]
    elif((6 <= row <= 8) and (3 <= col <= 5)):
        subarr = arr[6:9, 3:6]
    elif((3 <= row <= 5) and (6 <= col <= 8)):
        subarr = arr[3:6, 6:9]
    elif((6 <= row <= 8) and (6 <= col <= 8)):
        subarr = arr[6:9, 6:9]
    else:
        print('ERROR IN3x3 FNC')       

    subarr = subarr.reshape(9)
 
    for item in subarr:
        if (item == num):
            i = True
            break

    return i    
#}

#checks if there are still any zeroes in the array
def issolved(arr):
#{
    i = True

    for x in range(0,9):
        for y in range(0,9):
            if (arr[x,y] == 0):
                i = False
                break
    return i               
#}

def findfirstzero(arr):
#{
    if not issolved(arr):
        for x in range(0,9):
            for y in range(0,9):
                if (arr[x,y] == 0):
                    return x, y
                    break
#    else:
#        raw_input()
#}

#get the array of possible values in position xy
def getValues(arr, x, y):
#{
    values = []
    for i in range(1,10):
        if ((not inrow(arr,x,i)) and (not incol(arr,y,i)) and (not in3x3(arr,y,x,i))):
            values.append(i)
    return values
#}

#solving method: checks if the empty slot can have only one value and assigns that value to the slot
def methodEmptyCheck(arr,change):
#{
    change = 0  #counts how many things did this function change
    for x in range(0,9):      #x = row
        for y in range(0,9):  #y = col
            values = [] #an array of possible values
            if (arr[x,y] == 0): #if position x,y is empty
                values = getValues(arr, x, y)
                if (len(values) == 1): #if there is only one possible solution
                    arr[x, y] = values[0] #enter it in the array, else do nothing
                    change=change+1
                    #return change
                        #break
    return change
#} 

def methodIntersection(arr,change):
#{
    #change = 0
    for x in range(0,9):      #x = row
        for y in range(0,9):  #y = col
            values = [] #an array of possible values
            if (arr[x,y] == 0): #if x,y is empty
                for i in range(1,10):
                #{
                    if ((not inrow(arr,x,i)) and (not incol(arr,y,i)) and (not in3x3(arr,y,x,i))):
                        values.append(i)
                #}
                if (len(values) > 1): #if there is more than one possible value, check both surrounding rows for matches
                        for j in values:
                        #{
                            if ((x == 0) or (x == 3) or (x == 6)): #find the surrounding rows
                                if (inrow(arr,x+1,j) and inrow(arr,x+2,j)) and (incol(arr,x+1,j) and incol(arr,x+2,j)):
                                #if there is a match on the surrounding rows and columns
                                        arr[x,y] = j
                                        return 1
                            elif ((x == 1) or (x == 4) or (x == 7)): 
                                if (inrow(arr,x-1,j) and inrow(arr,x+1,j)) and (incol(arr,x-1,j) and incol(arr,x+1,j)):
                                        arr[x,y] = j
                                        return 1
                            elif ((x == 2) or (x == 5) or (x == 8)): 
                                if (inrow(arr,x-1,j) and inrow(arr,x-2,j)) and (incol(arr,x-1,j) and incol(arr,x-2,j)):
                                        arr[x,y] = j
                                        return 1
                        #}
    return 0
#}

def repeatEmptyCheck(arr, count):
#{
    change=0
    count = 1
    methodEmptyCheck(arr,change)

    while (not issolved(arr)):
        count = count+1

        if (methodEmptyCheck(arr,change)==0):
            #if (methodIntersection(newArr,change)==0):
            #    print("D: | tried:", count, 'iterations')
            break
    return
#}

     

repeatEmptyCheck(newArr, count)   
#if (issolved(newArr)):
#print('array is solved using', count, 'iterations')
print(count)
print(newArr)
#else:

print(findfirstzero(newArr))
x,y=findfirstzero(newArr)
values = getValues(newArr, x,y)
print(values)

#try one item from values
newArr[x,y]=values[-1]
#try to solve again
repeatEmptyCheck(newArr, count) 

print(newArr)
    
    
#write to file    
#outfilename = infilename + '_soln'
#newfile = open(outfilename, 'w')

#for row in range(0,9):
#    for col in range(0,9):
#        newfile.write(str(newArr[row][col]))
#        if (col%3 == 2):
#            newfile.write(" ")
#    if (row%3 == 2):
#        newfile.write(" ")
#        newfile.write("\n")
        
#    newfile.write("\n")

#newfile.close()

4
[[0 0 0 5 2 7 0 0 0]
 [0 0 2 4 9 6 3 0 0]
 [0 9 4 3 1 8 7 2 0]
 [2 7 5 1 3 9 4 6 8]
 [9 8 3 6 5 4 1 7 2]
 [1 4 6 0 0 2 5 9 3]
 [0 6 0 0 4 1 0 5 0]
 [0 0 9 2 0 5 6 0 0]
 [0 0 0 9 0 3 0 0 0]]
(0, 0)
[3, 6, 8]
[[8 3 1 5 2 7 9 4 6]
 [7 5 2 4 9 6 3 8 1]
 [6 9 4 3 1 8 7 2 5]
 [2 7 5 1 3 9 4 6 8]
 [9 8 3 6 5 4 1 7 2]
 [1 4 6 8 7 2 5 9 3]
 [3 6 8 7 4 1 2 5 9]
 [4 1 9 2 8 5 6 3 7]
 [5 2 7 9 6 3 8 1 4]]
