In [1]:
import numpy as np
initArr = np.empty([81], dtype=int) 

infilename = 'sudoku6'
file = open(infilename, 'r')

i=0
c = file.read(1)
while len(c) > 0:
    if len(c.strip()) > 0: 
        initArr[i]=c
        i=i+1
    c = file.read(1)    
file.close()

newArr = initArr.reshape(9,9)

def writeArr(newArr, infilename):
#{
    outfilename = infilename + '_soln'
    newfile = open(outfilename, 'w')

    for row in range(0,9):
        for col in range(0,9):
            newfile.write(str(newArr[row][col]))
            if (col%3 == 2):
                newfile.write(" ")
        if (row%3 == 2):
            newfile.write(" ")
            newfile.write("\n")
        
        newfile.write("\n")

    newfile.close()
#}

def incol (arr, col, num):
#{
    if num == 0:
        print('ERROR INCOL FNC')
        
    i = False
    for item in arr[:,col]:
        if item == num:
            i = True
            break
    return i
#}

def inrow (arr, row, num):
#{
    if num == 0:
        print('ERROR INROW FNC')
    
    i = False
    for item in arr[row]:
        if item == num:
            i = True
            break
    return i    
#}

def get3x3(arr,row,col):
#{
    if  ((0 <= row <= 2) and (0 <= col <= 2)):
        return arr[0:3, 0:3]
    elif((3 <= row <= 5) and (0 <= col <= 2)):
        return arr[3:6, 0:3]
    elif((6 <= row <= 8) and (0 <= col <= 2)):
        return arr[6:9, 0:3]    
    elif((0 <= row <= 2) and (3 <= col <= 5)):
        return arr[0:3, 3:6]    
    elif((0 <= row <= 2) and (6 <= col <= 8)):
        return arr[0:3, 6:9]            
    elif((3 <= row <= 5) and (3 <= col <= 5)):
        return arr[3:6, 3:6]
    elif((6 <= row <= 8) and (3 <= col <= 5)):
        return arr[6:9, 3:6]
    elif((3 <= row <= 5) and (6 <= col <= 8)):
        return arr[3:6, 6:9]
    elif((6 <= row <= 8) and (6 <= col <= 8)):
        return arr[6:9, 6:9]
    else:
        print ("ERROR IN GET3x3")
        return
#}

def in3x3 (arr, col, row, num):
#{
    if num == 0:
        print('ERROR IN3X3 FNC')
        
    i = False
    subarr = get3x3(arr,row,col)
    subarr = subarr.reshape(9)
 
    for item in subarr:
        if (item == num):
            i = True
            break

    return i    
#}

def isvalid(arr, row, col, num):
#{
    return ((not in3x3(arr, col, row, num)) and (not incol (arr, col, num)) and (not inrow (arr, row, num)))
#}

def recursudoku(arr, row, col):
#{
    #{ exit conditions
    if (row == 9):
        return 1
    
    if (arr[row][col] != 0):
        if (col == 8):
            if (recursudoku(arr, row+1, 0)): 
                return 1
        else:
            if (recursudoku(arr, row, col+1)): 
                return 1
        
        return 0
    #}

    for i in range(1,10):
        if(isvalid(arr, row, col, i)):
            arr[row][col] = i
            if (col == 8):
                if (recursudoku(arr, row+1, 0)):
                    return 1
            else:
                if (recursudoku(arr, row, col+1)): 
                    return 1
            
            arr[row][col] = 0

#}

recursudoku(newArr, 0, 0)

if (recursudoku(newArr, 0, 0) == 1):
    print(newArr)
    writeArr(newArr, infilename)
else:
    print("no solution found")

[[4 6 2 8 5 9 7 3 1]
 [1 9 7 2 6 3 8 4 5]
 [5 8 3 7 1 4 2 9 6]
 [8 3 4 9 2 1 5 6 7]
 [7 5 6 3 4 8 9 1 2]
 [2 1 9 6 7 5 3 8 4]
 [3 2 5 1 8 6 4 7 9]
 [9 7 1 4 3 2 6 5 8]
 [6 4 8 5 9 7 1 2 3]]
